spring:
  application:
    name: moviestar
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moviedb.c986m0iy09wc.ap-northeast-2.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: wlgjs566@gmail.com
    password: jhdnqrqkcjmqigvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 5000

tmdb:
  api:
    key: 8d8920fedcb7032d3b2b649d89e9d00f

